name: Publish Docker image for new releases

on:
  push:
    branches: [workshop]
  pull_request:
    branches: [workshop]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: scripts/Dockerfile
          tags: |
            onfinality/xxx:${{ steps.vars.outputs.sha_short }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Update image version of the existing network spec
        uses: "OnFinality-io/action-onf-release@v1"
        with:
          # These keys should be in your GitHub secrets
          onf-access-key: "THc4hqtMNPVgLZwXtjO2PJQDkKETFpYA"
          onf-secret-key: "KhD6kp3Y3KejNeP3DH+sMTT4od20oUC0UCB0U6dk"
          onf-workspace-id: "6683212593101979648"
          onf-network-key: b27bcdd4-fee0-44a2-9dae-62006051ef48
          # Add a new image version to network spec
          onf-sub-command: image
          onf-action: add
          image-version: ${{ steps.vars.outputs.sha_short }}

      - name: Perform a rolling upgrade to all nodes
        uses: "OnFinality-io/action-onf-release@v1"
        with:
          # These keys should be in your GitHub secrets
          onf-access-key: "THc4hqtMNPVgLZwXtjO2PJQDkKETFpYA"
          onf-secret-key: "KhD6kp3Y3KejNeP3DH+sMTT4od20oUC0UCB0U6dk"
          onf-workspace-id: "6683212593101979648"
          onf-network-key: b27bcdd4-fee0-44a2-9dae-62006051ef48
          # Perform a rolling ugrade to nodes
          onf-sub-command: node
          onf-action: upgrade
          image-version: ${{ steps.vars.outputs.sha_short }}
          percent: 30 # Percent of nodes to update at each time
